# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: DayOne
title: OneMonthProject - 3 devs 30 days 3 apps
email: contact@dayone.pl
description: OneMonthProject - 3 developers building 3 separate mobile apps in 30 days
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://onemonthproject.com" # the base hostname & protocol for your site
twitter_username: 1mthproject
keywords: "onemonth,developers,project,experiment,mobile,apps,ios,android,react,native,react native,small studio,custom software,software"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
